# Generated by Django 4.2.13 on 2024-06-13 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('golf_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hole',
            name='score',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='golf_app.score'),
        ),
    ]
