# Generated by Django 4.2.13 on 2024-06-13 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf_app', '0004_alter_hole_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='strokes',
            field=models.IntegerField(null=True),
        ),
    ]
