# Generated by Django 4.2.13 on 2024-06-15 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('golf_app', '0005_alter_score_strokes'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='hole',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='holes', to='golf_app.hole'),
        ),
    ]
